version: '3.7'
services:
  sync:
    depends_on:
      - ari
      - auth
      - calld
      - rabbitmq
    environment:
      TARGETS: "ari:5039 rabbitmq:5672 auth:9497 calld:9500"

  calld:
    volumes:
      - ./etc/wazo-calld/conf.d/20-ari-quick-reconnect.yml:/etc/wazo-calld/conf.d/20-ari-quick-reconnect.yml
