# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files to the extra_config_files directory to override
# the settings in this file

# Directory in which to place config overrides
extra_config_files: /etc/wazo-calld/conf.d/

# Change the log level to debug level.
debug: false

# Log file.
logfile: /var/log/wazo-calld.log

# REST API server
rest_api:

  # Address to listen on
  listen: 127.0.0.1

  # Port to listen on
  port: 9500

  # CORS configuration. See Flask-CORS documentation for other values.
  cors:

    # Enabled by default
    enabled: True

    # Allow JSON preflight requests
    allow_headers: [Content-Type, X-Auth-Token, Wazo-Tenant]

  # Maximum of concurrent threads processing requests
  # See the performance documentation for more details
  # https://wazo-platform.org/uc-doc/system/performance/
  max_threads: 10

# wazo-auth (authentication daemon) connection settings.
auth:
  host: localhost
  port: 9497
  prefix: null
  https: false
  key_file: /var/lib/wazo-auth-keys/wazo-calld-key.yml

# wazo-confd connection settings
confd:
  host: localhost
  port: 9486
  prefix: null
  https: false

# Event bus (AMQP) connection settings
bus:
  username: guest
  password: guest
  host: localhost
  port: 5672
  exchange_name: wazo-headers

# Event bus exchange for collectd (statistics)
collectd:
  exchange_name: collectd

# Asterisk ARI connection settings
ari:
  connection:
    base_url: http://localhost:5039
    username: xivo
    password: Nasheow8Eag

  # How many seconds between each try to reconnect to ARI
  reconnection_delay: 10

  # How many seconds between each try to connect to ARI at startup
  startup_connection_delay: 1

# wazo-amid connection settings
amid:
    host: localhost
    port: 9491
    prefix: null
    https: false

# wazo-phoned connection settings
phoned:
    host: localhost
    port: 9498
    prefix: null
    https: false

enabled_plugins:
  adhoc_conferences: true
  api: true
  applications: true
  calls: true
  dial_mobile: true
  relocates: true
  status: true
  switchboards: true
  transfers: true
  voicemails: true

service_discovery:
  enabled: false

# Example settings to enable service discovery
#
# Necessary to use service discovery
# consul:
#   scheme: http
#   host: consul.example.com
#   port: 8500
#   token: 'the_one_ring'
#
# # All time intervals are in seconds
# service_discovery:
#   # Indicates whether of not to use service discovery.
#   enabled: true
#   # The address that will be received by other services using service discovery.
#   # Use "advertise_address: auto" to enable ip address detection based on
#   # advertise_address_interface
#   advertise_address: auto
#   # If advertise_address is "auto" this interface will be used to find the ip
#   # address to advertise. Ignored otherwise
#   advertise_address_interface: eth0
#   advertise_port: 9500
#   # The number of seconds that consul will wait between 2 ttl messages to mark
#   # this service as up
#   ttl_interval: 30
#   # The time interval before the service sends a new ttl message to consul
#   refresh_interval: 27
#   # The time interval to detect that the service is running when starting
#   retry_interval: 2
#   extra_tags: []
