FROM wazoplatform/wazo-calld

ENV PYTHONDONTWRITEBYTECODE='true'

ADD . /usr/src/wazo-calld
WORKDIR /usr/src/wazo-calld

RUN python3 -m pip install -e . coverage[toml]
CMD ["coverage", "run", "--data-file", "/tmp/coverage", "/opt/venv/bin/wazo-calld"]
