FROM wazoplatform/wazo-calld

ENV PYTHONDONTWRITEBYTECODE='true'

RUN install -dm777 /usr/share/asterisk/voicemail
ADD ./integration_tests/assets/voicemails/8000 /var/spool/asterisk/voicemail/default/8000

ADD . /usr/src/wazo-calld
WORKDIR /usr/src/wazo-calld

RUN python3 -m pip install -e .
